version: '3'
services:
  # PostgreSQL database
  postgres:
    profiles:
      - ''
      - 'backend'
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mlflow}
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # MinIO server
  minio:
    profiles:
      - ''
      - 'backend'
    image: minio/minio
    expose:
      - "9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
  minio-create-bucket:
      image: minio/mc
      profiles:
        - ''
        - 'backend'
      depends_on:
        minio:
          condition: service_healthy
      entrypoint: >
        bash -c "
        mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID:-minioadmin} ${AWS_SECRET_ACCESS_KEY:-minioadmin} &&
        if ! mc ls minio | grep --quiet ${AWS_BUCKET:-mlruns}; then
          mc mb minio/${AWS_BUCKET:-mlruns}
        else
          echo 'bucket already exists'
        fi
        "
  mlflow-server:
    profiles:
      - ''
      - 'frontend'
    image: mlflow-server:latest
    build:
      context: .
      dockerfile: Dockerfile-mlflow
    ports:
      - 5000:5000
    networks:
      - frontend
      - backend
    volumes:
      - ./entrypoint-mlflow.sh:/entrypoint-mlflow.sh
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
      AWS_BUCKET: ${AWS_BUCKET:-mlruns}
      POSTGRES_URI: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-mlflow}
    entrypoint: /entrypoint-mlflow.sh

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge