name: mlflow-practice
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - pip:
    - python-dotenv
    - awscli
    - -e .
    - hydra-core==1.3
    - scikit-learn
    - mlflow
    - psycopg2
    - boto3